server:
  port: 8005

spring:
  application:
    name: restaurant
  datasource:
    url: ${DB_URL_USER}
    username: ${DB_USERNAME_USER}
    password: ${DB_PASSWORD_USER}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true

  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs